---
title: Presentaciones puestas en blogdown
author: Martín Macías
date: '2018-03-01'
slug: presentaciones-puestas-en-blogdown
summary: Diferencia entre Merging y Rebasing
categories:
  - blogdown
tags:
  - presentations
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE, collapse = TRUE, comment = NA, tidy = FALSE)
```

# blogdown + rmarkdown = ¡impresionante!

## _Reproducir archivos Rmd en un sitio web construido con blogdown_

Este es un pequeño ejemplo que muestra cómo puede reproducirse cualquier archivo Rmd en una página web construida con [**blogdown**](https://github.com/rstudio/blogdown). La clave es agregar un script de R, llamado `build.R` dentro de una carpeta llamada `R/` (este archivo únicamente tiene una línea de código: `blogdown::build_dir('static')`), y poner los archivos Rmd dentro de la carpeta `static/`. Vea la breve documentación al respecto en el [libro de **blogdown**](https://bookdown.org/yihui/blogdown/static-files.html).

No importa qué formatos de salida generen sus Rmd; `build_dir()` llamará la función `rmarkdown::render()` para reproducirlos. En este blog, hay dos ejemplos (Se requieren los paquetes de R [**xaringan**](https://github.com/yihui/xaringan) and [**bookdown**](https://github.com/rstudio/bookdown)):


- Generación de presentación HTML5 basada en **xaringan**: [slides/xaringan.html](/slides/xaringan.html) (Rmd de origen: [static/slides/xaringan.Rmd](https://github.com/yihui/blogdown-static/blame/master/static/slides/xaringan.Rmd)).

- Generación de un documento PDF usando el formato `bookdown::pdf_document2`: [pdf/example.pdf](/pdf/example.pdf) (Rmd de origen: [static/pdf/example.Rmd](https://github.com/yihui/blogdown-static/blame/master/static/pdf/example.Rmd)).